name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
    branches:
     - main
    paths:
      .github/workflows/profile.yaml
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_rss: yes
          plugin_rss_source: https://sredevops.cl/rss/
          plugin_rss_limit: 5
          filename: metrics.plugin.rss.svg
